<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class DataDocumentMasuk extends Seeder
{
	public function run()
	{
		$documentmasuk = [
			[
				'documentmasuk_id'			=> 1,
				'kode_dokumen'			=> 'DK22+657.44',
				'document_type'			=> 'BRIDGE',
				'document_number'		=> 'JBHSR-1-RB-B-DR-004-03',
				'judul_dokumen'			=> 'CONSTRUCTION DRAWING DESIGN DK226 BRIDGE MILEAGE DK22+657.44',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-08',
				'karyawan_id'			=> 2,
			],
			[
				'documentmasuk_id'			=> 2,
				'kode_dokumen'			=> 'DK18+134.10-DK18+589.09',
				'document_type'			=> 'BRIDGE',
				'document_number'		=> 'JBHSR-1-RB-B-DR-004-04',
				'judul_dokumen'			=> 'CONSTRUCTION DRAWING DESIGN DK226 BRIDGE MILEAGE DK22+657.44 (DK18+134.10-DK18+589.09)',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-08',
				'karyawan_id'			=> 2,
			],
			[
				'documentmasuk_id'			=> 3,
				'kode_dokumen'			=> 'DIK115+244.60~DIK116+585.35',
				'document_type'			=> 'BRIDGE',
				'document_number'		=> 'JBHSR-1-RB-DR-031-01',
				'judul_dokumen'			=> 'SUPER MAJOR BRIDGE (DIK115+244.60~DIK116+585.35)',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-08',
				'karyawan_id'			=> 3,
			],
			[
				'documentmasuk_id'			=> 4,
				'kode_dokumen'			=> 'DK48+641.50~DK49+529.50',
				'document_type'			=> 'BRIDGE',
				'document_number'		=> 'JBHSR-1-RB-DR-008',
				'judul_dokumen'			=> 'CONSTRUCTION DRAWING DESIGN (CONSULTING EDITION) DK490 BRIDGE MILEAGE DK49+085.50',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-07',
				'karyawan_id'			=> 2,
			],
			[
				'documentmasuk_id'			=> 5,
				'kode_dokumen'			=> 'DK75+540~DK76+275',
				'document_type'			=> 'TUNNEL NO.3',
				'document_number'		=> 'JBHSR-1-TR-DR-03-01~08',
				'judul_dokumen'			=> 'Design Drawing of Tunnel No. 3',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-06',
				'karyawan_id'			=> 4,
			],
			[
				'documentmasuk_id'			=> 6,
				'kode_dokumen'			=> 'DK74+010 - DK76+895',
				'document_type'			=> 'ALIGNMENT',
				'document_number'		=> 'JBHSR-1-RL-DR-02-01-01',
				'judul_dokumen'			=> 'ALIGNMENT PLAN DK74+010 - DK76+895',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-06',
				'karyawan_id'			=> 4,
			],
			[
				'documentmasuk_id'			=> 7,
				'kode_dokumen'			=> 'DK75+050.00-DK75+105.16',
				'document_type'			=> 'SUBGRADE',
				'document_number'		=> 'JBHSR-1-RS-DR-11',
				'judul_dokumen'			=> 'SUBGRADE CONSTRUCTION DRAWING DK75+050.00-DK75+105.16',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-06',
				'karyawan_id'			=> 4,
			],
			[
				'documentmasuk_id'			=> 8,
				'kode_dokumen'			=> 'DK31+016.56~DK32+733.66',
				'document_type'			=> 'BRIDGE',
				'document_number'		=> 'JBHSR-1-RB-DR-004-06',
				'judul_dokumen'			=> 'DK226 EXTRA LARGE BRIDGE（DK31+016.56~DK32+733.66）',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-06',
				'karyawan_id'			=> 2,
			],
			[
				'documentmasuk_id'			=> 9,
				'kode_dokumen'			=> 'DK85+043.00~DK85+228.32',
				'document_type'			=> 'BRIDGE',
				'document_number'		=> 'JBHSR-1-RB-DR-023',
				'judul_dokumen'			=> 'DK851 LARGE BRIDGE（DK85+043.00~DK85+228.32）',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-05',
				'karyawan_id'			=> 3,
			],
			[
				'documentmasuk_id'			=> 10,
				'kode_dokumen'			=> 'DK96+124.03',
				'document_type'			=> 'CULVERT',
				'document_number'		=> 'JBHSR-1-RB-B-DR-004-03',
				'judul_dokumen'			=> '1-3,0m Reinforced Concrete Frame Box Culvert',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-04',
				'karyawan_id'			=> 3,
			],
			[
				'documentmasuk_id'			=> 11,
				'kode_dokumen'			=> 'DK22+154.44',
				'document_type'			=> 'BRIDGE',
				'document_number'		=> 'JBHSR-1-RB-B-DR-004-04',
				'judul_dokumen'			=> 'C1-3,0m Reinforced Concrete Frame Box Culvert(DK22+154.44)',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-04',
				'karyawan_id'			=> 3,
			],
			[
				'documentmasuk_id'			=> 12,
				'kode_dokumen'			=> 'DK87+1544.42',
				'document_type'			=> 'BRIDGE',
				'document_number'		=> 'JBHSR-1-RB-B-DR-005-03',
				'judul_dokumen'			=> 'CONSTRUCTION DRAWING DESIGN DK143 BRIDGE MILEAGE DK87+1544.44',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-04',
				'karyawan_id'			=> 2,
			],
			[
				'documentmasuk_id'			=> 13,
				'kode_dokumen'			=> 'DK545+654.33',
				'document_type'			=> 'BRIDGE',
				'document_number'		=> 'JBHSR-1-RB-B-DR-004-03',
				'judul_dokumen'			=> 'CONSTRUCTION DRAWING DESIGN DK142 BRIDGE MILEAGE DK545+654.33',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-04',
				'karyawan_id'			=> 2,
			],
			[
				'documentmasuk_id'			=> 14,
				'kode_dokumen'			=> 'DK65+432.12',
				'document_type'			=> 'SUBGRADE',
				'document_number'		=> 'JBHSR-1-RS-DR-14',
				'judul_dokumen'			=> 'SUBGRADE CONSTRUCTION DRAWING DDK65+432.12-DK75+105.16',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-04',
				'karyawan_id'			=> 2,
			],
			[
				'documentmasuk_id'			=> 15,
				'kode_dokumen'			=> 'DK14+541.15',
				'document_type'			=> 'SUBGRADE',
				'document_number'		=> 'JBHSR-1-RS-DR-13',
				'judul_dokumen'			=> 'SUBGRADE CONSTRUCTION DRAWING DK75+050.00-DK14+541.15',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-04',
				'karyawan_id'			=> 4,
			],
			[
				'documentmasuk_id'			=> 16,
				'kode_dokumen'			=> 'DK66+212.13',
				'document_type'			=> 'SUBGRADE',
				'document_number'		=> 'JBHSR-1-RS-DR-12',
				'judul_dokumen'			=> 'SUBGRADE CONSTRUCTION DRAWING DK66+212.13+105.16',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-04',
				'karyawan_id'			=> 4,
			],
			[
				'documentmasuk_id'			=> 17,
				'kode_dokumen'			=> 'DK78+132.45',
				'document_type'			=> 'BRIDGE',
				'document_number'		=> 'JBHSR-1-RB-B-DR-004-13',
				'judul_dokumen'			=> 'CONSTRUCTION DRAWING DESIGN DK226 BRIDGE MILEAGE DK78+132.45',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-03',
				'karyawan_id'			=> 4,
			],
			[
				'documentmasuk_id'			=> 18,
				'kode_dokumen'			=> 'DK154+312.44',
				'document_type'			=> 'TUNNEL NO.3',
				'document_number'		=> 'JBHSR-1-TR-DR-03-01~18',
				'judul_dokumen'			=> 'Design Drawing of Tunnel No. 3 (DK154+312.44)',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-03',
				'karyawan_id'			=> 3,
			],
			[
				'documentmasuk_id'			=> 19,
				'kode_dokumen'			=> 'DK154+312.44',
				'document_type'			=> 'TUNNEL NO.3',
				'document_number'		=> 'JBHSR-1-TR-DR-03-01~28',
				'judul_dokumen'			=> 'Design Drawing of Tunnel No. 3 (DK154+312.44)',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-03',
				'karyawan_id'			=> 3,
			],
			[
				'documentmasuk_id'			=> 20,
				'kode_dokumen'			=> 'DK14+784.16',
				'document_type'			=> 'TUNNEL NO.3',
				'document_number'		=> 'JBHSR-1-TR-DR-03-02~08',
				'judul_dokumen'			=> 'Design Drawing of Tunnel No. 3(DK14+784.16)',
				'vendor'				=> 'KJB',
				'bahasa'				=> 'ENGLISH & CHINESE',
				'status_document'		=> 'Masuk',
				'tanggal_masuk'			=> '2021-06-03',
				'karyawan_id'			=> 3,
			],
		];
		$this->db->table('documentmasuk')->insertBatch($documentmasuk);
	}
}
